### ISSUE TITLE
Can Cura use it?

### ISSUE THREAD

**Issue by leezoneline** [abra5umente/Ender3S1Configs#1]
this start up Gcode and end Gcode is full of some variable values. I wonder that whether I can copy it to my Cura directly or not.

**Comment by abra5umente** [comment]
> this start up Gcode and end Gcode is full of some variable values. I wonder that whether I can copy it to my Cura directly or not.

You could use it if you adapt the variables to what Cura expects. I'm not 100% sure what Cura uses as I've never used it, but I'm sure there is a guide to what variables they use and how it works out there somewhere.

**Comment by leezoneline** [comment]
ok, thanks
